services:
  - type: web
    name: culturebenin
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan storage:link
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
    startCommand: ""
    envVars:
      - key: APP_NAME
        value: CultureBenin
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: error
      - key: LOG_CHANNEL
        value: stack

      # DB AIVEN
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-1d3a9ed-tianrymareol330-f73e.j.aivencloud.com
      - key: DB_PORT
        value: "14657"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        scope: secret

      # SSL pour Aiven
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt

      # SESSION / CACHE
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local

      # MAIL
      - key: MAIL_MAILER
        value: log